# Generated by Django 4.0.5 on 2023-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluus', '0002_alter_profile_cover_photo_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/pics/default_dp.png', upload_to='post-pic/'),
        ),
    ]
