# Generated by Django 4.0.5 on 2022-06-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluus', '0003_alter_profile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
