# Generated by Django 4.0.5 on 2022-06-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluus', '0005_alter_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='post-pic/'),
        ),
    ]
