# Generated by Django 4.0.5 on 2023-06-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluus', '0005_alter_profile_cover_photo_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='default_c_pic.jpg', upload_to='media/post-pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default_dp.png', upload_to='media/post-pic'),
        ),
    ]
