# Generated by Django 4.0.5 on 2022-06-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluus', '0007_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, default='/post-pic/default_c_pic.jpg', upload_to='post-pic/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/post-pic/default_dp.png', upload_to='post-pic/'),
        ),
    ]
