# Generated by Django 4.0.5 on 2022-06-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluus', '0009_comment_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=69, null=True),
        ),
    ]
