# Generated by Django 4.0.5 on 2022-06-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluus', '0011_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('In a relationship', 'In a relationship'), ('Engaged', 'Engaged'), ("It's complicated", "It's complicated")], max_length=69, null=True),
        ),
    ]
